from .auth import router as auth_router
from .employees import router as employees_router
from .assets import router as assets_router
from .categories import router as categories_router
from .licenses import router as licenses_router
from .repairs import router as repairs_router
from .announcements import router as announcements_router
from .guidelines import router as guidelines_router
from .notifications import router as notifications_router
from .activity import router as activity_router
from .dashboard import router as dashboard_router
